name: Run PHPUnit tests

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: laravel
        ports:
          - 3307:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        volumes:
          - /var/lib/mysql

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer

      - name: Install dependencies
        run: composer install

      - name: Set permissions for storage and cache
        run: |
          chmod -R 775 storage bootstrap/cache
          chown -R www-data:www-data storage bootstrap/cache

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Wait for MySQL to be ready
        run: |
          until nc -z -v -w30 mysql 3306
          do
            echo "Waiting for MySQL connection..."
            sleep 1
          done
          echo "MySQL is ready!"

      - name: Start Laravel Sail
        run: |
          vendor/bin/sail up -d
          vendor/bin/sail artisan migrate --seed

      - name: Run tests
        run: vendor/bin/sail phpunit

      - name: Stop Laravel Sail
        if: always()
        run: vendor/bin/sail down
